name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  # deploy:
  #   name: Deploy
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@master
  #     - name: Download Artifact
  #       uses: actions/download-artifact@master
  #       with:
  #         name: dist
  #         path: dist
  #     - name: Deploy to Firebase
  #       uses: w9jds/firebase-action@master
  #       with:
  #         args: deploy --only hosting
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.SAMPLESECRET }}
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACESS_SECRET }}
          aws-region: ap-southeast-2

      ### backup the existing build to backup bucket ###
      - name: copy the current version to backup bucket
        run: aws s3 cp s3://irentaa-dev-webapp s3://irentaa-dev-bucket/BuildBackups/WebApp/irentaa_bak_$(date '+%Y-%m-%d') --recursive

      ### deploy the website #######
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/GitHubActionsWithNg s3://irentaa-dev-webapp
